import {beforeEach,expect,it,vi} from "vitest";
import {createHmac} from "node:crypto";
import {NextRequest} from "next/server";
const {send,query,rpc}=vi.hoisted(()=>({send:vi.fn(),query:{select:vi.fn(),eq:vi.fn(),maybeSingle:vi.fn()},rpc:vi.fn()}));
vi.mock("../lib/supabase-server",()=>({supabaseServer:()=>({from:()=>query,rpc})}));
vi.mock("../lib/line-booking-notification",()=>({sendLineBookingNotification:send}));
import {encryptLineCredential} from "../lib/line-settings-secret";
import {POST} from "../app/api/line/webhook/[storeId]/route";
const storeId="11111111-1111-1111-1111-111111111111";
const context={params:Promise.resolve({storeId})};
function request(events:unknown[],secret="secret"){const body=JSON.stringify({events});return new NextRequest("http://localhost/api/line/webhook/"+storeId,{method:"POST",body,headers:{"x-line-signature":createHmac("sha256",secret).update(body).digest("base64")}});}
beforeEach(()=>{vi.resetAllMocks();vi.stubEnv("LINE_SETTINGS_ENCRYPTION_KEY","b".repeat(64));query.select.mockReturnValue(query);query.eq.mockReturnValue(query);query.maybeSingle.mockResolvedValue({data:{channel_secret_cipher:encryptLineCredential(storeId,"secret"),access_token_cipher:encryptLineCredential(storeId,"access")},error:null});rpc.mockResolvedValue({data:null,error:null});});
it("rejects forged signature before mutations",async()=>{expect((await POST(request([],"wrong"),context)).status).toBe(401);expect(rpc).not.toHaveBeenCalled();});
it("accepts LINE verification empty events",async()=>{expect((await POST(request([]),context)).status).toBe(200);expect(rpc).not.toHaveBeenCalled();});
it("uses signed direct-message source and hashes the code",async()=>{const event={type:"message",source:{type:"user",userId:"U"+"a".repeat(32)},message:{type:"text",text:"予約連携 "+"b".repeat(32)}};expect((await POST(request([event]),context)).status).toBe(200);expect(rpc).toHaveBeenCalledWith("consume_customer_line_notification_code",{p_store_id:storeId,p_code_hash:expect.stringMatching(/^[a-f0-9]{64}$/),p_line_user_id:event.source.userId});expect(JSON.stringify(rpc.mock.calls)).not.toContain("b".repeat(32));});
it("ignores group messages and unrelated content",async()=>{expect((await POST(request([{type:"message",source:{type:"group",userId:"U"+"a".repeat(32)},message:{type:"text",text:"予約連携 "+"b".repeat(32)}}]),context)).status).toBe(200);expect(rpc).not.toHaveBeenCalled();});
it("signals database failure for LINE retry without leaking internals",async()=>{rpc.mockResolvedValue({error:{message:"secret"}});const r=await POST(request([{type:"message",source:{type:"user",userId:"U"+"a".repeat(32)},message:{type:"text",text:"予約連携 "+"b".repeat(32)}}]),context);expect(r.status).toBe(503);expect(await r.text()).toBe("");});

it("sends queued notification and records acceptance",async()=>{const job={storeId,userId:"U"+"a".repeat(32),codeHash:"c".repeat(64),retryKey:"retry"};rpc.mockResolvedValueOnce({data:job,error:null}).mockResolvedValueOnce({data:null,error:null});const event={type:"message",source:{type:"user",userId:job.userId},message:{type:"text",text:"予約連携 "+"b".repeat(32)}};expect((await POST(request([event]),context)).status).toBe(200);expect(send).toHaveBeenCalledWith(job,"access");expect(rpc).toHaveBeenLastCalledWith("mark_line_booking_notification_sent",{p_store_id:storeId,p_code_hash:job.codeHash,p_retry_key:job.retryKey});});
it("retains pending notification on send failure and rejects wrong-recipient jobs",async()=>{const event={type:"message",source:{type:"user",userId:"U"+"a".repeat(32)},message:{type:"text",text:"予約連携 "+"b".repeat(32)}};rpc.mockResolvedValue({data:{storeId,userId:event.source.userId},error:null});send.mockRejectedValue(new Error("private"));expect((await POST(request([event]),context)).status).toBe(503);expect(rpc).toHaveBeenCalledTimes(1);rpc.mockClear();send.mockClear();rpc.mockResolvedValue({data:{storeId:"other",userId:event.source.userId},error:null});expect((await POST(request([event]),context)).status).toBe(503);expect(send).not.toHaveBeenCalled();});
