-- Apply after 0010. Tokens are generated by the server; only hashes are stored.
begin;
create table if not exists customer_booking_access (
  token_hash text primary key check (token_hash ~ '^[a-f0-9]{64}$'),
  reservation_id uuid not null unique references reservations(id) on delete cascade,
  store_id uuid not null references stores(id), expires_at timestamptz not null
);
alter table customer_booking_access enable row level security;
revoke all on customer_booking_access from public, anon, authenticated, service_role;
grant select on customer_booking_access to service_role;

create or replace function issue_customer_booking_access(p_store_id uuid, p_reservation_id uuid, p_token_hash text)
returns void language plpgsql security definer set search_path = public as $$
declare v_reservation reservations;
begin
  if p_token_hash is null or p_token_hash !~ '^[a-f0-9]{64}$' then raise exception 'invalid_token'; end if;
  select * into v_reservation from reservations where id=p_reservation_id and store_id=p_store_id for no key update;
  if not found then raise exception 'booking_not_found'; end if;
  delete from customer_booking_access where reservation_id=p_reservation_id;
  insert into customer_booking_access values (p_token_hash,p_reservation_id,p_store_id,
    greatest(clock_timestamp() + interval '400 days',v_reservation.end_at + interval '30 days'));
end; $$;

create or replace function create_customer_booking_atomic(
  p_store_id uuid, p_service_id uuid, p_staff_id uuid, p_start_at timestamptz,
  p_customer_name text, p_customer_phone text, p_source reservation_source,
  p_note text, p_customer_email text, p_token_hash text
) returns reservations language plpgsql security definer set search_path = public as $$
declare v_reservation reservations;
begin
  v_reservation := create_reservation_with_email_atomic(p_store_id,p_service_id,p_staff_id,
    p_start_at,p_customer_name,p_customer_phone,p_source,p_note,p_customer_email);
  perform issue_customer_booking_access(p_store_id,v_reservation.id,p_token_hash);
  return v_reservation;
end; $$;

create or replace function read_customer_booking(p_token_hash text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_result jsonb;
begin
  select jsonb_build_object('id',r.id,'storeId',r.store_id,'storeName',s.name,
    'serviceId',r.service_id,'serviceName',sv.name,'staffId',r.staff_id,'staffName',st.name,
    'customerName',c.name,'startAt',r.start_at,'endAt',r.end_at,
    'status',r.status,'updatedAt',r.updated_at,
    'canManage',r.status='confirmed' and r.start_at>clock_timestamp())
  into v_result from customer_booking_access a join reservations r on r.id=a.reservation_id and r.store_id=a.store_id
  join stores s on s.id=r.store_id join services sv on sv.id=r.service_id
  join staff st on st.id=r.staff_id join customers c on c.id=r.customer_id
  where a.token_hash=p_token_hash and a.expires_at>clock_timestamp();
  if v_result is null then raise exception 'booking_not_found'; end if;
  return v_result;
end; $$;

create or replace function manage_customer_booking_atomic(
  p_token_hash text, p_action text, p_expected_updated_at timestamptz,
  p_start_at timestamptz default null
) returns jsonb language plpgsql security definer set search_path = public as $$
declare v_access customer_booking_access; v_original reservations; v_result reservations;
  v_days integer; v_cutoff integer; v_now timestamptz;
begin
  select * into v_access from customer_booking_access where token_hash=p_token_hash and expires_at>clock_timestamp();
  if not found then raise exception 'booking_not_found'; end if;
  -- Same store/staff lock order as booking creation.
  select advance_days,cutoff_minutes into v_days,v_cutoff from stores where id=v_access.store_id for no key update;
  select * into v_original from reservations where id=v_access.reservation_id and store_id=v_access.store_id;
  if not found then raise exception 'booking_not_found'; end if;
  if v_original.status <> 'confirmed' or v_original.updated_at is distinct from p_expected_updated_at then raise exception 'booking_changed'; end if;
  if p_action = 'reschedule' then
    if p_start_at is null or not isfinite(p_start_at) then raise exception 'invalid_start_time'; end if;
    -- Existing RPC handles 15-minute grid, buffers, assignments, hours and conflicts.
    v_result := reschedule_reservation_atomic(v_access.store_id,v_original.id,v_original.staff_id,p_start_at,p_expected_updated_at);
    v_now := clock_timestamp();
    if v_original.start_at <= v_now then raise exception 'booking_closed'; end if;
    if p_start_at <= v_now or p_start_at < v_now + make_interval(mins=>v_cutoff)
      or (p_start_at at time zone 'Asia/Tokyo')::date > (v_now at time zone 'Asia/Tokyo')::date + v_days then
      raise exception 'booking_window_closed';
    end if;
  elsif p_action = 'cancel' then
    select * into v_original from reservations where id=v_access.reservation_id and store_id=v_access.store_id for update;
    if v_original.status <> 'confirmed' or v_original.updated_at is distinct from p_expected_updated_at then raise exception 'booking_changed'; end if;
    if v_original.start_at <= clock_timestamp() then raise exception 'booking_closed'; end if;
    update reservations set status='cancelled',updated_at=clock_timestamp()
      where id=v_original.id and store_id=v_access.store_id returning * into v_result;
  else raise exception 'invalid_action';
  end if;
  -- Re-check revocation/expiry after waits. A concurrent reissue invalidates this operation.
  perform 1 from customer_booking_access where token_hash=p_token_hash and expires_at>clock_timestamp();
  if not found then raise exception 'booking_not_found'; end if;
  return read_customer_booking(p_token_hash);
end; $$;

revoke all on function issue_customer_booking_access(uuid,uuid,text) from public,anon,authenticated;
revoke all on function create_customer_booking_atomic(uuid,uuid,uuid,timestamptz,text,text,reservation_source,text,text,text) from public,anon,authenticated;
revoke all on function read_customer_booking(text) from public,anon,authenticated;
revoke all on function manage_customer_booking_atomic(text,text,timestamptz,timestamptz) from public,anon,authenticated;
grant execute on function issue_customer_booking_access(uuid,uuid,text) to service_role;
grant execute on function create_customer_booking_atomic(uuid,uuid,uuid,timestamptz,text,text,reservation_source,text,text,text) to service_role;
grant execute on function read_customer_booking(text) to service_role;
grant execute on function manage_customer_booking_atomic(text,text,timestamptz,timestamptz) to service_role;
commit;
